name: Generate Insights

# Ставим только чтение встроенному токену,
# чтобы не было лишних прав, и явно используем PAT для записи.
permissions:
  contents: read

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  generate-insights:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (read-only)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: false

      - name: Configure push access via PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Ensure 'insights' branch exists
        run: |
          git fetch origin insights || echo "No 'insights' branch found"
          git checkout insights || git checkout -b insights

      - name: Generate GitHub Insights
        uses: emillg/github-repo-insights@v1.1.0
        with:
          repos: "source-Alexander-Rudenko/vk_ads_test"
          pat-token: ${{ secrets.PAT_TOKEN }}

      - name: Commit and push insights
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update GitHub Insights" || echo "No changes to commit"
          git push origin insights
